In [3]:
# Task 1
import numpy as np

# Створюємо матрицю коефіцієнтів
A = np.array([[0.05, 0.07, 0], [0.05, 0, 0.06], [1, 1, 1]])

# Створюємо вектор правої частини
B = np.array([2250, 1400, 50000])

# Розв'язуємо систему рівнянь
X = np.linalg.solve(A, B)

# Виводимо результат
print(X)

#Task 2
import numpy as np

A = np.array([[1, 1, 1], [1, -1, 0], [1, 0, -1]])
b = np.array([1328, 120, -100])
x = np.linalg.inv(A).dot(b)
y = np.array(x)
x_rounded = np.round(y).astype(int)

print(x)
print(x_rounded)
#Task 3
import numpy as np

# задані точки A, B та C
A = np.array([np.sqrt(3), 0, np.sqrt(3)])
B = np.array([np.sqrt(6), 1/2, 0])
C = np.array([1, 1/np.sqrt(3), 1])

# знаходимо вектори сторін еліпсоїда
AB = B - A
AC = C - A

# знаходимо вектор нормалі до площини еліпсоїда
n = np.cross(AB, AC)

# знаходимо параметри a^2, b^2 та c^2
a2 = np.linalg.norm(AC) ** 2 / (2 * (1 - np.dot(AB, AC) ** 2 / (np.linalg.norm(AB) ** 2 * np.linalg.norm(AC) ** 2)))
b2 = np.linalg.norm(np.cross(n, AB)) ** 2 / np.linalg.norm(AB) ** 2
c2 = np.linalg.norm(n) ** 2 / np.linalg.norm(AB) ** 2

# виводимо результат
print("a^2 =", a2)
print("b^2 =", b2)
print("c^2 =", c2)
print()

# знаходимо параметри a, b та c
a = np.sqrt(a2)
b = np.sqrt(b2)
c = np.sqrt(c2)

# виводимо результат
print("a =", a)
print("b =", b)
print("c =", c)

#Task 4
import numpy as np

# Заданные точки
points = np.array([[1, 12], [3, 54], [-1, 2]])

# Матрица коэффициентов
A = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])

# Столбец свободных членов
B = np.array([12, 54, 2])

# Решение системы уравнений
coeffs = np.linalg.solve(A, B)

# Вывод коэффициентов
print("a = {}, b = {}, c = {}".format(coeffs[0], coeffs[1], coeffs[2]))

#Task 5
import numpy as np  # Import the NumPy library

def get_polynom(coords):                # Define a function that takes in a list of coordinate tuples
    n = len(coords) - 1                 # Determine the degree of the polynomial
    A = np.zeros((n+1, n+1))            # Initialize a matrix A of zeros with dimensions (n+1) x (n+1)
    b = np.zeros((n+1, 1))              # Initialize a vector b of zeros with dimensions (n+1) x 1
    for i in range(n+1):                # Loop over the rows of A and b
        for j in range(n+1):            # Loop over the columns of A
            A[i,j] = coords[i][0]**j    # Set the i,jth entry of A to x_i^j
        b[i] = coords[i][1]             # Set the ith entry of b to y_i
    return np.linalg.solve(A, b)        # Solve the system of linear equations and return the coefficients of the polynomial

coords = np.random.random((4, 4))       # Define a list of coordinate tuples
print(coords)
coefs = get_polynom(coords)                     # Call the get_polynom function and store the coefficients in coefs
print(coefs)                            # Print the coefficients of the polynomial


[10000. 25000. 15000.]
[449.33333333 329.33333333 549.33333333]
[449 329 549]
a^2 = 0.8794216958470753
b^2 = 4.226086942130732
c^2 = 1.1225505442059402

a = 0.9377748641582773
b = 2.055744863092386
c = 1.059504858037914
a = 4.0, b = 5.0, c = 3.0
[[0.37563974 0.83149011 0.98149983 0.71276815]
 [0.1636677  0.24202603 0.03293704 0.09347691]
 [0.8388636  0.77854482 0.22210756 0.25327963]
 [0.13984998 0.0494737  0.83976563 0.40373602]]
[[ -1.81988894]
 [ 18.47678926]
 [-40.18046636]
 [ 26.04364108]]
