In [15]:
# Task 1
import numpy as np

# Створюємо матрицю коефіцієнтів
A = np.array([[0.05, 0.07, 0], [0.05, 0, 0.06], [1, 1, 1]])

# Створюємо вектор правої частини
B = np.array([2250, 1400, 50000])

# Розв'язуємо систему рівнянь
X = np.linalg.solve(A, B)
x_rounded = np.round(X).astype(int)
# Виводимо результат
print('result witout formating: ', X)
print("first bank = {}, second bank = {}, third bank = {}".format(x_rounded[0], x_rounded[1], x_rounded[2]))

result witout formating:  [10000. 25000. 15000.]
first bank = 10000, second bank = 25000, third bank = 15000


In [22]:
#Task 2
import numpy as np

A = np.array([[1, 1, 1], [1, -1, 0], [1, 0, -1]])
b = np.array([1328, 120, -100])
x = np.linalg.inv(A).dot(b)
y = np.array(x)
x_rounded = np.round(y).astype(int)

print('result witout formating: ', x)
print("iPhone 6 = {}, iPhone 11 = {}, iPhone 12 = {}".format(x_rounded[0], x_rounded[1], x_rounded[2]))
print(sum(x_rounded))

result witout formating:  [449.33333333 329.33333333 549.33333333]
iPhone 6 = 449, iPhone 11 = 329, iPhone 12 = 549
1327


In [19]:
#Task 3
import numpy as np

# задані точки A, B та C
A = np.array([np.sqrt(3), 0, np.sqrt(3)])
B = np.array([np.sqrt(6), 1/2, 0])
C = np.array([1, 1/np.sqrt(3), 1])

# знаходимо вектори сторін еліпсоїда
AB = B - A
AC = C - A

# знаходимо вектор нормалі до площини еліпсоїда
n = np.cross(AB, AC)

# знаходимо параметри a^2, b^2 та c^2
a2 = np.linalg.norm(AC) ** 2 / (2 * (1 - np.dot(AB, AC) ** 2 / (np.linalg.norm(AB) ** 2 * np.linalg.norm(AC) ** 2)))
b2 = np.linalg.norm(np.cross(n, AB)) ** 2 / np.linalg.norm(AB) ** 2
c2 = np.linalg.norm(n) ** 2 / np.linalg.norm(AB) ** 2

# виводимо результат
print("a^2 =", a2)
print("b^2 =", b2)
print("c^2 =", c2)
print()

# знаходимо параметри a, b та c
a = np.sqrt(a2)
b = np.sqrt(b2)
c = np.sqrt(c2)

# виводимо результат
print("a =", a)
print("b =", b)
print("c =", c)


a^2 = 0.8794216958470753
b^2 = 4.226086942130732
c^2 = 1.1225505442059402

a = 0.9377748641582773
b = 2.055744863092386
c = 1.059504858037914


In [3]:
#Task 4
import numpy as np

# Заданные точки
points = np.array([[1, 12], [3, 54], [-1, 2]])

# Матрица коэффициентов
A = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])

# Столбец свободных членов
B = np.array([12, 54, 2])

# Решение системы уравнений
coeffs = np.linalg.solve(A, B)

# Вывод коэффициентов
print("a = {}, b = {}, c = {}".format(coeffs[0], coeffs[1], coeffs[2]))

a = 4.0, b = 5.0, c = 3.0


In [24]:
#Task 5
import numpy as np  # Import the NumPy library

def get_polynom(coords):                        # Define a function that takes in a list of coordinate tuples
    n = len(coords) - 1                         # Determine the degree of the polynomial
    A = np.zeros((n+1, n+1))                    # Initialize a matrix A of zeros with dimensions (n+1) x (n+1)
    b = np.zeros((n+1, 1))                      # Initialize a vector b of zeros with dimensions (n+1) x 1
    for i in range(n+1):                        # Loop over the rows of A and b
        for j in range(n+1):                    # Loop over the columns of A
            A[i,j] = coords[i][0]**j            # Set the i,jth entry of A to x_i^j
        b[i] = coords[i][1]                     # Set the ith entry of b to y_i
    return np.linalg.solve(A, b)                # Solve the system of linear equations and return the coefficients of the polynomial

coords = np.random.random((4, 4))               # Define a list of coordinate tuples
print('Random coords:', coords, sep='\n')
coefs = get_polynom(coords)                     # Call the get_polynom function and store the coefficients in coefs
print('Result: ', coefs, sep='\n')                            # Print the coefficients of the polynomial

Random coords:
[[0.2901932  0.13224557 0.62369505 0.54422608]
 [0.82010656 0.0395368  0.94404934 0.23857629]
 [0.67434156 0.38500177 0.5849131  0.76868382]
 [0.83275187 0.58523598 0.79327766 0.26041927]]
Result: 
[[ -87.873224  ]
 [ 539.20124513]
 [-969.79679525]
 [ 540.21090052]]
