<a href="https://colab.research.google.com/github/Viktor-Skobeliev/DS_hw/blob/main/HW1_ds9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
array = []
for i in range(1, 11):
    array.append(i)

print(array)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
matrix = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

for row in matrix:
    print(row)


[0, 0, 0]
[0, 0, 0]
[0, 0, 0]


In [4]:
import random

matrix = [[random.randint(1, 10) for _ in range(5)] for _ in range(5)]

for row in matrix:
    print(row)


[10, 3, 9, 4, 1]
[7, 9, 1, 8, 10]
[9, 10, 7, 9, 7]
[2, 8, 4, 3, 1]
[10, 5, 7, 1, 7]


In [5]:
import random

matrix = [[random.random() for _ in range(4)] for _ in range(4)]

for row in matrix:
    print(row)


[0.288812587371692, 0.06735743816269546, 0.8551579428734737, 0.44690328962837855]
[0.21826761982537823, 0.8139432581694407, 0.5655431579271561, 0.5413996223392147]
[0.2833770876071541, 0.9709477773747284, 0.1588354533384405, 0.14145512580194253]
[0.621677643928051, 0.012017906759275832, 0.18072238971716315, 0.3454378422924418]


In [6]:
import random

array1 = [random.randint(1, 10) for _ in range(5)]
array2 = [random.randint(1, 10) for _ in range(5)]

print("Масив 1:", array1)
print("Масив 2:", array2)

result_addition = [x + y for x, y in zip(array1, array2)]
result_subtraction = [x - y for x, y in zip(array1, array2)]
result_multiplication = [x * y for x, y in zip(array1, array2)]

print("Результат додавання:", result_addition)
print("Результат віднімання:", result_subtraction)
print("Результат множення:", result_multiplication)


Масив 1: [1, 5, 1, 2, 4]
Масив 2: [9, 2, 2, 2, 5]
Результат додавання: [10, 7, 3, 4, 9]
Результат віднімання: [-8, 3, -1, 0, -1]
Результат множення: [9, 10, 2, 4, 20]


In [7]:
import random

vector1 = [random.randint(1, 10) for _ in range(7)]
vector2 = [random.randint(1, 10) for _ in range(7)]

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

dot_product = sum(x * y for x, y in zip(vector1, vector2))

print("Скалярний добуток:", dot_product)


Вектор 1: [10, 3, 3, 10, 10, 8, 10]
Вектор 2: [5, 3, 8, 1, 8, 1, 9]
Скалярний добуток: 271


In [8]:
import random
import numpy as np

matrix1 = np.random.randint(1, 10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 3))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("Результат множення:")
print(result)


Матриця 1:
[[3 3]
 [6 8]]
Матриця 2:
[[3 3 7]
 [4 4 3]]
Результат множення:
[[21 21 30]
 [50 50 66]]


In [9]:
import random
import numpy as np

matrix = np.random.randint(1, 10, size=(3, 3))

print("Початкова матриця:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не є оборотною.")


Початкова матриця:
[[1 1 4]
 [1 3 4]
 [2 7 2]]
Обернена матриця:
[[ 1.83333333 -2.16666667  0.66666667]
 [-0.5         0.5        -0.        ]
 [-0.08333333  0.41666667 -0.16666667]]


In [10]:
import random
import numpy as np

matrix = np.random.rand(4, 4)

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("Транспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[0.11859682 0.01926574 0.58070725 0.29886255]
 [0.7431872  0.90653375 0.04170654 0.83103539]
 [0.48785642 0.65924166 0.60705212 0.54955805]
 [0.09287186 0.25698896 0.02963907 0.53566648]]
Транспонована матриця:
[[0.11859682 0.7431872  0.48785642 0.09287186]
 [0.01926574 0.90653375 0.65924166 0.25698896]
 [0.58070725 0.04170654 0.60705212 0.02963907]
 [0.29886255 0.83103539 0.54955805 0.53566648]]


In [11]:
import random
import numpy as np

matrix = np.random.randint(1, 10, size=(3, 4))
vector = np.random.randint(1, 10, size=(4,))

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

result = np.dot(matrix, vector)

print("Результат перемноження:")
print(result)


Матриця:
[[7 6 6 6]
 [3 3 1 7]
 [2 5 9 7]]
Вектор:
[8 3 1 5]
Результат перемноження:
[110  69  75]


In [12]:
import random
import numpy as np

matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

result = np.dot(matrix, vector)

print("Результат перемноження:")
print(result)


Матриця:
[[0.63863612 0.67156463 0.95184648]
 [0.72875294 0.22045351 0.21238004]]
Вектор:
[0.32898055 0.75674542 0.84492827]
Результат перемноження:
[1.52254432 0.58601863]


In [13]:
import random
import numpy as np

matrix1 = np.random.randint(1, 10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.multiply(matrix1, matrix2)

print("Результат поелементного множення:")
print(result)


Матриця 1:
[[6 3]
 [1 1]]
Матриця 2:
[[4 1]
 [2 4]]
Результат поелементного множення:
[[24  3]
 [ 2  4]]


In [14]:
import random
import numpy as np

matrix1 = np.random.randint(1, 10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("Результат добутку матриць:")
print(result)


Матриця 1:
[[6 5]
 [6 7]]
Матриця 2:
[[1 4]
 [9 9]]
Результат добутку матриць:
[[51 69]
 [69 87]]


In [15]:
import random
import numpy as np

matrix = np.random.randint(1, 101, size=(5, 5))

print("Матриця:")
print(matrix)

sum_of_elements = np.sum(matrix)

print("Сума елементів матриці:", sum_of_elements)


Матриця:
[[60  1 83 15 43]
 [56 97 98  2  6]
 [83 66 97 19 33]
 [27 55 71 20 72]
 [47 47 21 16 45]]
Сума елементів матриці: 1180


In [16]:
import random
import numpy as np

matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

difference = matrix1 - matrix2

print("Різниця матриць:")
print(difference)


Матриця 1:
[[ 7  8  2  1]
 [ 6  2  3  3]
 [10  2  2  5]
 [ 2  5  1  7]]
Матриця 2:
[[ 1  9  7  8]
 [ 4  4 10  9]
 [ 9  9  3  6]
 [10  2  6 10]]
Різниця матриць:
[[ 6 -1 -5 -7]
 [ 2 -2 -7 -6]
 [ 1 -7 -1 -1]
 [-8  3 -5 -3]]


In [17]:
import numpy as np

matrix = np.random.random((3, 3))

print("Матриця:")
print(matrix)

row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape((-1, 1))

print("Вектор-стовпчик з сумами рядків:")
print(column_vector)


Матриця:
[[0.36816819 0.70463996 0.81937152]
 [0.46020446 0.31681325 0.89426848]
 [0.93444529 0.95097378 0.30103459]]
Вектор-стовпчик з сумами рядків:
[[1.89217968]
 [1.67128618]
 [2.18645366]]


In [18]:
import numpy as np

matrix = np.random.randint(1, 10, size=(3, 4))
squared_matrix = np.square(matrix)

print("Початкова матриця:")
print(matrix)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)


Початкова матриця:
[[8 5 5 5]
 [2 2 3 1]
 [7 5 1 6]]

Матриця з квадратами чисел:
[[64 25 25 25]
 [ 4  4  9  1]
 [49 25  1 36]]


In [19]:
import numpy as np

vector = np.random.randint(1, 50, size=4)
sqrt_vector = np.sqrt(vector)

print("Початковий вектор:")
print(vector)
print("\nВектор з квадратними коренями чисел:")
print(sqrt_vector)


Початковий вектор:
[38 17 23 45]

Вектор з квадратними коренями чисел:
[6.164414   4.12310563 4.79583152 6.70820393]
